export const siteConfig = {
  name: 'MultiTools',
  description: 'Free online client-side and backend developer, image, and text tools to speed up your workflow.',
  url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  apiUrl: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api/v1',
  ogImage: 'https://multi-tools.com/og.png',
  author: 'MultiTools Inc',
  links: {
    github: 'https://github.com/tools-website',
    twitter: 'https://twitter.com/tools-website',
  },
  theme: {
    defaultTheme: 'system',
    storageKey: 'multi-tools-theme',
  },
  seo: {
    titleTemplate: '%s | MultiTools',
    defaultTitle: 'MultiTools - Free Online Multi-Tools Website',
    twitterCard: 'summary_large_image',
    openGraph: {
      type: 'website',
      locale: 'en_US',
      siteName: 'MultiTools',
    },
  },
  routes: {
    home: '/',
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    verifyEmail: '/verify-email',
    profile: '/profile',
    admin: {
      dashboard: '/admin',
      users: '/admin/users',
      categories: '/admin/categories',
      tools: '/admin/tools',
      settings: '/admin/settings',
    },
  },
  categories: [
    {
      id: 'developer-tools',
      name: 'Developer Tools',
      slug: 'developer-tools',
      description: 'Useful tools for formatting code, generating random data, and testing patterns.',
      icon: 'Code2',
    },
    {
      id: 'image-tools',
      name: 'Image Tools',
      slug: 'image-tools',
      description: 'Compress, convert, and generate visual images or QR codes.',
      icon: 'Image',
    },
    {
      id: 'text-tools',
      name: 'Text & Content Tools',
      slug: 'text-tools',
      description: 'Analyze, count, preview markdown and manipulate text blocks.',
      icon: 'FileText',
    },
    {
      id: 'color-tools',
      name: 'Color Tools',
      slug: 'color-tools',
      description: 'Pick colors, create gradients and generate palettes.',
      icon: 'Palette',
    },
    {
      id: 'crypto-tools',
      name: 'Crypto Tools',
      slug: 'crypto-tools',
      description: 'Track, search, and manage weekly Binance WODL words, calculators, and blockchain helpers.',
      icon: 'Coins',
    },
  ],
  tools: [
    {
      name: 'JSON Formatter',
      slug: 'json-formatter',
      category: 'developer-tools',
      description: 'Format, validate, parse, and beautify your JSON data with instant syntax errors visual warnings.',
      keywords: ['json', 'formatter', 'beautify', 'validator', 'lint', 'json parser'],
    },
    {
      name: 'UUID Generator',
      slug: 'uuid-generator',
      category: 'developer-tools',
      description: 'Generate secure, random UUIDs (v4) in bulk with custom spacing options.',
      keywords: ['uuid', 'guid', 'generator', 'uuid v4', 'random id'],
    },
    {
      name: 'Password Generator',
      slug: 'password-generator',
      category: 'developer-tools',
      description: 'Generate strong, secure passwords with custom character configurations and strength evaluation.',
      keywords: ['password', 'generator', 'random password', 'security', 'key generator'],
    },
    {
      name: 'QR Code Generator',
      slug: 'qr-generator',
      category: 'image-tools',
      description: 'Convert links, text, and email addresses into custom-sized downloadable SVGs or PNG QR codes.',
      keywords: ['qr code', 'generator', 'qr maker', 'qr code svg', 'qr barcode'],
    },
    {
      name: 'Base64 Encoder/Decoder',
      slug: 'base64',
      category: 'text-tools',
      description: 'Encode plain text to Base64 format or decode Base64 back into readable text.',
      keywords: ['base64', 'encoder', 'decoder', 'base64 translate', 'url safe base64'],
    },
    {
      name: 'Markdown Preview',
      slug: 'markdown-preview',
      category: 'text-tools',
      description: 'Write, preview, and format standard markdown text in a side-by-side split screen.',
      keywords: ['markdown', 'previewer', 'md editor', 'wysiwyg', 'markdown viewer'],
    },
    {
      name: 'Word Counter',
      slug: 'word-counter',
      category: 'text-tools',
      description: 'Analyze text content for counts of characters, words, paragraphs, lines, and reading speed.',
      keywords: ['word count', 'character count', 'count words', 'reading speed', 'text stats'],
    },
    {
      name: 'Color Picker & Gradient',
      slug: 'color-picker',
      category: 'color-tools',
      description: 'Interactive canvas color wheel, HEX/RGB conversions, and linear/radial CSS gradient builders.',
      keywords: ['color picker', 'gradient', 'css gradient', 'rgb to hex', 'palette builder'],
    },
    {
      name: 'Binance WODL Words',
      slug: 'binance-wodl',
      category: 'crypto-tools',
      description: 'Find the complete list of weekly Binance WODL / Word of the Day answers grouped by letters (3-8 letters). Search past themes, filter by length, and submit/update new weekly words.',
      keywords: ['binance wodl', 'binance word of the day', 'crypto wodl', 'wodl answers', 'wodl list'],
    },
    {
      name: 'Randomizer Wheel',
      slug: 'randomizer-wheel',
      category: 'text-tools',
      description: 'Interactive spin-the-wheel random picker with customizable entries, color palettes, sound effects, presets, and winner celebrations.',
      keywords: ['randomizer wheel', 'spin wheel', 'wheel of names', 'random picker', 'picker wheel', 'decision maker'],
    },
  ],
};
