const getValidUrl = (url?: string, defaultUrl = 'http://localhost:3000') => {
  if (!url) {
    if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
    return defaultUrl;
  }
  if (url.startsWith('http://') || url.startsWith('https://')) {
    return url;
  }
  return `https://${url}`;
};

export const siteConfig = {
  name: 'MultiTools',
  description: 'Free online client-side and backend developer, image, and text tools to speed up your workflow.',
  url: getValidUrl(process.env.NEXT_PUBLIC_APP_URL, 'http://localhost:3000'),
  apiUrl: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api/v1',
  ogImage: 'https://multi-tools.com/og.png',
  author: 'MultiTools Inc',
  links: {
    github: 'https://github.com/tools-website',
    twitter: 'https://twitter.com/tools-website',
  },
  theme: {
    defaultTheme: 'system',
    storageKey: 'multi-tools-theme',
  },
  seo: {
    titleTemplate: '%s | MultiTools',
    defaultTitle: 'MultiTools - Free Online Multi-Tools Website',
    twitterCard: 'summary_large_image',
    googleSiteVerification:
      process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION ||
      'ufoJM2dgEgRecmQlmZYdkHJORg7wko5nQTkyuC2qAtM',
    openGraph: {
      type: 'website',
      locale: 'en_US',
      siteName: 'MultiTools',
    },
  },
  routes: {
    home: '/',
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    verifyEmail: '/verify-email',
    profile: '/profile',
    admin: {
      dashboard: '/admin',
      users: '/admin/users',
      categories: '/admin/categories',
      tools: '/admin/tools',
      settings: '/admin/settings',
    },
  },
  categories: [
    {
      id: 'developer-tools',
      name: 'Developer Tools',
      slug: 'developer-tools',
      description: 'Useful tools for formatting code, generating random data, and testing patterns.',
      icon: 'Code2',
    },
    {
      id: 'image-tools',
      name: 'Image Tools',
      slug: 'image-tools',
      description: 'Compress, convert, and generate visual images or QR codes.',
      icon: 'Image',
    },
    {
      id: 'text-tools',
      name: 'Text & Content Tools',
      slug: 'text-tools',
      description: 'Analyze, count, preview markdown and manipulate text blocks.',
      icon: 'FileText',
    },
    {
      id: 'color-tools',
      name: 'Color Tools',
      slug: 'color-tools',
      description: 'Pick colors, create gradients and generate palettes.',
      icon: 'Palette',
    },
    {
      id: 'crypto-tools',
      name: 'Crypto Tools',
      slug: 'crypto-tools',
      description: 'Track, search, and manage weekly Binance WODL words, calculators, and blockchain helpers.',
      icon: 'Coins',
    },
    {
      id: 'study-tools',
      name: 'Study Tools',
      slug: 'study-tools',
      description: 'Productivity boosters, study session timers, and focus tools for students and professionals.',
      icon: 'GraduationCap',
    },
    {
      id: 'pdf-tools',
      name: 'PDF Tools',
      slug: 'pdf-tools',
      description: 'Free browser-based tools to merge, split, compress, convert, rotate, watermark, protect, and edit PDF documents locally.',
      icon: 'FileText',
    },
  ],
  tools: [
    {
      name: 'JSON Formatter',
      slug: 'json-formatter',
      category: 'developer-tools',
      description: 'Format, validate, parse, and beautify your JSON data with instant syntax errors visual warnings.',
      keywords: ['json', 'formatter', 'beautify', 'validator', 'lint', 'json parser'],
    },
    {
      name: 'UUID Generator',
      slug: 'uuid-generator',
      category: 'developer-tools',
      description: 'Generate secure, random UUIDs (v4) in bulk with custom spacing options.',
      keywords: ['uuid', 'guid', 'generator', 'uuid v4', 'random id'],
    },
    {
      name: 'Password Generator',
      slug: 'password-generator',
      category: 'developer-tools',
      description: 'Generate strong, secure passwords with custom character configurations and strength evaluation.',
      keywords: ['password', 'generator', 'random password', 'security', 'key generator'],
    },
    {
      name: 'QR Code Generator',
      slug: 'qr-generator',
      category: 'image-tools',
      description: 'Convert links, text, and email addresses into custom-sized downloadable SVGs or PNG QR codes.',
      keywords: ['qr code', 'generator', 'qr maker', 'qr code svg', 'qr barcode'],
    },
    {
      name: 'Base64 Encoder/Decoder',
      slug: 'base64',
      category: 'text-tools',
      description: 'Encode plain text to Base64 format or decode Base64 back into readable text.',
      keywords: ['base64', 'encoder', 'decoder', 'base64 translate', 'url safe base64'],
    },
    {
      name: 'Markdown Preview',
      slug: 'markdown-preview',
      category: 'text-tools',
      description: 'Write, preview, and format standard markdown text in a side-by-side split screen.',
      keywords: ['markdown', 'previewer', 'md editor', 'wysiwyg', 'markdown viewer'],
    },
    {
      name: 'Word Counter',
      slug: 'word-counter',
      category: 'text-tools',
      description: 'Analyze text content for counts of characters, words, paragraphs, lines, and reading speed.',
      keywords: ['word count', 'character count', 'count words', 'reading speed', 'text stats'],
    },
    {
      name: 'Color Picker & Gradient',
      slug: 'color-picker',
      category: 'color-tools',
      description: 'Interactive canvas color wheel, HEX/RGB conversions, and linear/radial CSS gradient builders.',
      keywords: ['color picker', 'gradient', 'css gradient', 'rgb to hex', 'palette builder'],
    },
    {
      name: 'Binance WODL Words',
      slug: 'binance-wodl',
      category: 'crypto-tools',
      description: 'Find the complete list of weekly Binance WODL / Word of the Day answers grouped by letters (3-8 letters). Search past themes, filter by length, and submit/update new weekly words.',
      keywords: ['binance wodl', 'binance word of the day', 'crypto wodl', 'wodl answers', 'wodl list'],
    },
    {
      name: 'Randomizer Wheel',
      slug: 'randomizer-wheel',
      category: 'text-tools',
      description: 'Interactive spin-the-wheel random picker with customizable entries, color palettes, sound effects, presets, and winner celebrations.',
      keywords: ['randomizer wheel', 'spin wheel', 'wheel of names', 'random picker', 'picker wheel', 'decision maker'],
    },
    {
      name: 'JWT Decoder & Inspector',
      slug: 'jwt-decoder',
      category: 'developer-tools',
      description: 'Decode JSON Web Tokens (Header, Payload, Signature), inspect claims, check expiration status, and format payload client-side.',
      keywords: ['jwt', 'jwt decoder', 'json web token', 'decode jwt', 'jwt parser', 'jwt expiry', 'token inspector'],
    },
    {
      name: 'Case Converter',
      slug: 'case-converter',
      category: 'text-tools',
      description: 'Convert text between camelCase, snake_case, kebab-case, CONSTANT_CASE, Title Case, PascalCase, and UPPERCASE instantly.',
      keywords: ['case converter', 'camelcase', 'snake case', 'kebab case', 'pascalcase', 'title case', 'text converter'],
    },
    {
      name: 'Lorem Ipsum Generator',
      slug: 'lorem-generator',
      category: 'text-tools',
      description: 'Generate customizable placeholder text by paragraphs, sentences, or words with optional HTML paragraph tags and download options.',
      keywords: ['lorem ipsum', 'placeholder text', 'text generator', 'dummy text', 'lorem generator', 'ipsum maker'],
    },
    {
      name: 'URL Slug Generator',
      slug: 'slug-generator',
      category: 'text-tools',
      description: 'Convert article titles or sentences into clean, SEO-friendly web URL slugs with custom separators and accent stripping.',
      keywords: ['url slug', 'slug generator', 'seo slug', 'clean url maker', 'title to slug', 'permalink generator'],
    },
    {
      name: 'HTML Entity Encoder / Decoder',
      slug: 'html-entity',
      category: 'text-tools',
      description: 'Encode plain text into HTML entities (&lt;, &gt;, &amp;) or decode entity strings back to readable characters.',
      keywords: ['html entity', 'html encoder', 'html decoder', 'encode html', 'escape html', 'html special characters'],
    },
    {
      name: 'Focus Timer',
      slug: 'focus-timer',
      category: 'study-tools',
      description: 'A customizable Pomodoro and focus timer with ambient wallpaper backgrounds, sound alerts, task lists, and customizable bottom settings.',
      keywords: ['focus timer', 'pomodoro', 'study timer', 'pomodoro technique', 'study wallpaper', 'focus mode', 'productivity timer'],
    },
    {
      name: 'Merge PDF',
      slug: 'merge-pdf',
      category: 'pdf-tools',
      description: 'Combine multiple PDF files into one single document. Reorder pages and merge directly in your browser with zero server uploads.',
      keywords: ['merge pdf', 'combine pdf files', 'combine pdfs', 'merge multiple pdfs', 'pdf merger', 'combine pdf documents', 'merge pdf online', 'free pdf merger'],
    },
    {
      name: 'Split PDF',
      slug: 'split-pdf',
      category: 'pdf-tools',
      description: 'Split PDF pages into standalone documents or extract custom page ranges quickly and securely client-side.',
      keywords: ['split pdf', 'split pdf online', 'split pdf pages', 'extract pdf pages', 'separate pdf pages', 'pdf splitter', 'split pdf file', 'divide pdf'],
    },
    {
      name: 'Compress PDF',
      slug: 'compress-pdf',
      category: 'pdf-tools',
      description: 'Reduce PDF file size with customizable compression levels (Low, Medium, High). Compare sizes and reduction percentage instantly.',
      keywords: ['compress pdf', 'compress pdf online', 'reduce pdf size', 'reduce pdf file size', 'pdf compressor', 'make pdf smaller', 'shrink pdf', 'compress pdf free'],
    },
    {
      name: 'PDF to JPG',
      slug: 'pdf-to-jpg',
      category: 'pdf-tools',
      description: 'Convert PDF pages into high-quality JPG images. Select individual pages or batch download all pages as a ZIP archive.',
      keywords: ['pdf to jpg', 'convert pdf to jpg', 'pdf to image', 'convert pdf pages to jpg', 'pdf jpg converter', 'save pdf as jpg', 'pdf to jpeg'],
    },
    {
      name: 'PDF to PNG',
      slug: 'pdf-to-png',
      category: 'pdf-tools',
      description: 'Convert PDF document pages into crisp, lossless PNG images with selective page extraction or complete ZIP download.',
      keywords: ['pdf to png', 'convert pdf to png', 'pdf image converter', 'pdf pages to png', 'save pdf as png', 'pdf png converter'],
    },
    {
      name: 'JPG to PDF',
      slug: 'jpg-to-pdf',
      category: 'pdf-tools',
      description: 'Convert JPG images into a clean PDF document. Reorder images, configure page orientation and margins before exporting.',
      keywords: ['jpg to pdf', 'convert jpg to pdf', 'jpg pdf converter', 'images to pdf', 'combine jpg into pdf', 'create pdf from jpg', 'jpg to pdf online'],
    },
    {
      name: 'PNG to PDF',
      slug: 'png-to-pdf',
      category: 'pdf-tools',
      description: 'Transform multiple PNG image files into a single, polished PDF file with drag-and-drop reordering and layout control.',
      keywords: ['png to pdf', 'convert png to pdf', 'png pdf converter', 'images to pdf', 'create pdf from png', 'combine png images into pdf'],
    },
    {
      name: 'Rotate PDF',
      slug: 'rotate-pdf',
      category: 'pdf-tools',
      description: 'Rotate PDF pages permanently by 90°, 180°, or 270°. Rotate individual selected pages or rotate all pages in one click.',
      keywords: ['rotate pdf', 'rotate pdf online', 'rotate pdf pages free', 'turn pdf', 'change pdf orientation'],
    },
    {
      name: 'Watermark PDF',
      slug: 'watermark-pdf',
      category: 'pdf-tools',
      description: 'Add custom text watermarks to your PDF pages. Customize font size, opacity, rotation angle, color, and positioning.',
      keywords: ['watermark pdf', 'add watermark to pdf', 'watermark pdf online', 'stamp pdf', 'protect pdf with watermark'],
    },
    {
      name: 'Add Page Numbers',
      slug: 'add-page-numbers-to-pdf',
      category: 'pdf-tools',
      description: 'Add clean page numbers to PDF documents with customizable positioning (top, bottom, left, center, right), starting number, and font size.',
      keywords: ['add page numbers to pdf', 'number pdf pages', 'pdf page numbering', 'paginate pdf', 'insert page numbers pdf'],
    },
    {
      name: 'Extract PDF Pages',
      slug: 'extract-pdf-pages',
      category: 'pdf-tools',
      description: 'Select specific pages from an existing PDF and generate a brand-new document containing only the chosen pages.',
      keywords: ['extract pdf pages', 'extract pages from pdf', 'save specific pdf pages', 'export pages from pdf', 'select pdf pages'],
    },
    {
      name: 'Reorder PDF Pages',
      slug: 'reorder-pdf-pages',
      category: 'pdf-tools',
      description: 'Rearrange and sort PDF page order visually with thumbnail previews and drag-and-drop reordering controls.',
      keywords: ['reorder pdf pages', 'rearrange pdf pages', 'organize pdf', 'sort pdf pages', 'change pdf page order'],
    },
    {
      name: 'Password Protect PDF',
      slug: 'password-protect-pdf',
      category: 'pdf-tools',
      description: 'Secure your PDF files with strong client-side AES encryption and passwords to prevent unauthorized viewing and access.',
      keywords: ['password protect pdf', 'encrypt pdf', 'lock pdf', 'secure pdf', 'add password to pdf'],
    },
    {
      name: 'Unlock PDF',
      slug: 'unlock-pdf',
      category: 'pdf-tools',
      description: 'Remove password protection from authorized PDFs so you can freely view, edit, and print without entering credentials every time.',
      keywords: ['unlock pdf', 'remove pdf password', 'decrypt pdf', 'unprotect pdf', 'open password protected pdf'],
    },
    {
      name: 'Edit PDF Metadata',
      slug: 'edit-pdf-metadata',
      category: 'pdf-tools',
      description: 'View and modify PDF document metadata including Title, Author, Subject, Keywords, Creator, and Producer tags.',
      keywords: ['edit pdf metadata', 'change pdf title', 'pdf author editor', 'view pdf metadata', 'pdf properties editor'],
    },
    {
      name: 'Crop PDF',
      slug: 'crop-pdf',
      category: 'pdf-tools',
      description: 'Crop PDF page margins, trim white borders, and preview dimensions before applying changes to individual or all pages.',
      keywords: ['crop pdf', 'trim pdf margins', 'crop pdf pages', 'cut pdf borders', 'adjust pdf size'],
    },
    {
      name: 'Grayscale PDF',
      slug: 'grayscale-pdf',
      category: 'pdf-tools',
      description: 'Convert full-color PDF pages into clean black-and-white or grayscale documents to reduce printer ink and file sizes.',
      keywords: ['grayscale pdf', 'convert pdf to black and white', 'monochrome pdf', 'bw pdf', 'print friendly pdf'],
    },
    {
      name: 'Extract Text from PDF',
      slug: 'extract-text-from-pdf',
      category: 'pdf-tools',
      description: 'Extract all digital text content from PDF pages instantly with one-click clipboard copy and TXT download.',
      keywords: ['extract text from pdf', 'pdf to text', 'copy text from pdf', 'pdf text extractor', 'read pdf text'],
    },
    {
      name: 'PDF OCR',
      slug: 'ocr-pdf',
      category: 'pdf-tools',
      description: 'Optical Character Recognition for scanned PDFs and document images. Recognize non-selectable text directly in your browser.',
      keywords: ['ocr pdf', 'scanned pdf to text', 'searchable pdf', 'optical character recognition pdf', 'extract text from scanned pdf'],
    },
    {
      name: 'Sign PDF',
      slug: 'sign-pdf',
      category: 'pdf-tools',
      description: 'Add drawn, typed, or uploaded electronic signatures to any page in your PDF document quickly and privately.',
      keywords: ['sign pdf', 'add signature to pdf', 'sign pdf online', 'electronic signature pdf', 'draw signature on pdf'],
    },
  ],
};
